Repository ljharb/tape, pull requests merged in 2019-01, with the labels that each got.

#411 add alias 'notDeepEquals' to 'notDeepEqual' function
  lib/test.js
  readme.markdown
Labels: enhancement

#240 Add electron-tap
  readme.markdown
Labels: needs "allow edits"

#329 Show failure location even if windows driver letter is lowercase
  lib/test.js
Labels: enhancement

#404 Fix #105: only use one test runner for results, even if multiple streams are created
  lib/results.js
  test/create_multiple_streams.js
Labels: semver-patch: bugfixes/etc

#361 Stop createStream for creating additional test runner loops
  lib/results.js
Labels: semver-patch: bugfixes/etc
